name: visible_block
version: '1.0-a'
main: cn.tenflake.vblock.Vblock

commands:
  visible:
    description: 通过发包控制方块是否可见
    permission: vblock.op
    usage: /visibleblock x y z Block player true/false[false为空气]
  visibleblocks:
    description: 多个
    permission: vblock.op
    usage: /visibleblocks x1 y1 z1 x2 y2 z2 Block player true/false空气
  savedata:
    description: eee save all player data
    permission: vblock.op
    usage: 辅助用的存储所有玩家信息

depend:
  - ProtocolLib